import type { IncomingMessage, ServerResponse } from 'http';
// Static import so esbuild bundles the compiled NestJS app + all its deps into the Lambda.
// dist/ is generated by `nest build` (postinstall) before esbuild runs on Vercel.
// api/ is excluded from tsconfig.build.json so nest only compiles src/ -> dist/.
import { createApp } from '../dist/app-factory.js';

let expressApp: any;

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  if (!expressApp) {
    const app = await createApp();
    await app.init();
    expressApp = app.getHttpAdapter().getInstance();
  }
  expressApp(req, res);
}
